### ISSUE TITLE
Exception in peeler_engine_geometry.py

### ISSUE THREAD

**Issue by magland** [tridesclous/tridesclous#146]
Do you recognize the below error? I get it when I run this spikeforest2 test: https://github.com/magland/spikeforest2/blob/master/working/tests/test_tridesclous_32c.py

```
tridesclous 2019-12-17T12:47:28.593646: Traceback (most recent call last):
tridesclous 2019-12-17T12:47:28.593684:   File "/run_in_container/run.py", line 15, in main
tridesclous 2019-12-17T12:47:28.593689:     retval = tridesclous(**kwargs)
tridesclous 2019-12-17T12:47:28.593695:   File "/run_in_container/function_src/_tridesclous.py", line 36, in tridesclous
tridesclous 2019-12-17T12:47:28.593699:     timer = sorter.run()
tridesclous 2019-12-17T12:47:28.593705:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line 110, in run
tridesclous 2019-12-17T12:47:28.593709:     self._run(recording, self.output_folders[i])
tridesclous 2019-12-17T12:47:28.593715:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/tridesclous/tridesclous.py", line 171, in _run
tridesclous 2019-12-17T12:47:28.593719:     peeler.run(duration=None, progressbar=False)
tridesclous 2019-12-17T12:47:28.593724:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peeler.py", line 152, in run_offline_all_segment
tridesclous 2019-12-17T12:47:28.593728:     self.run_offline_loop_one_segment(seg_num=seg_num, **kargs)
tridesclous 2019-12-17T12:47:28.593734:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peeler.py", line 125, in run_offline_loop_one_segment
tridesclous 2019-12-17T12:47:28.593738:     sig_index, preprocessed_chunk, total_spike, spikes = self.peeler_engine.process_one_chunk(pos, sigs_chunk)
tridesclous 2019-12-17T12:47:28.593744:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_base.py", line 271, in process_one_chunk
tridesclous 2019-12-17T12:47:28.593747:     spike = self.classify_and_align_next_spike(peak_ind, peak_chan)
tridesclous 2019-12-17T12:47:28.593753:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_base.py", line 402, in classify_and_align_next_spike
tridesclous 2019-12-17T12:47:28.593757:     cluster_idx, shift = self.get_best_template(left_ind, peak_chan)
tridesclous 2019-12-17T12:47:28.593763:   File "/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_geometry.py", line 353, in get_best_template
tridesclous 2019-12-17T12:47:28.593766:     if s[cluster_idx] > self.max_float32:
tridesclous 2019-12-17T12:47:28.593777: AttributeError: 'PeelerEngineGeometrical' object has no attribute 'max_float32'
```

**Comment by samuelgarcia** [comment]
Hi Jeremy,
this errors was fixed in 1.3.2 if I remmeber corectly.
Did you instaled 1.3.3 ?

**Comment by magland** [comment]
Thanks, I am updating the dockerfile now.

**Comment by magland** [comment]
I seem to still be getting the same error after upgrading to 1.3.3 (unless
i am making some docker cache mistake)

**Comment by magland** [comment]
I am also seeing the following error for one of the spikeforest datasets:

```
tridesclous 2019-12-17T14:38:13.332942: ###### RUNNING:
tridesclous:paired_kampff/c46
tridesclous 2019-12-17T14:38:16.506317: Sorting...
tridesclous 2019-12-17T14:42:17.587153: make_catalogue
tridesclous 2019-12-17T14:42:17.587251:
tridesclous 2019-12-17T14:42:17.587272: 0.424652608926408
tridesclous 2019-12-17T14:42:21.486387: Traceback (most recent call last):
tridesclous 2019-12-17T14:42:21.486576:   File "/run_in_container/run.py",
line 15, in main
tridesclous 2019-12-17T14:42:21.486586:     retval = tridesclous(**kwargs)
tridesclous 2019-12-17T14:42:21.486593:   File
"/run_in_container/function_src/_tridesclous.py", line 36, in tridesclous
tridesclous 2019-12-17T14:42:21.486598:     timer = sorter.run()
tridesclous 2019-12-17T14:42:21.486604:   File
"/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line
110, in run
tridesclous 2019-12-17T14:42:21.486609:     self._run(recording,
self.output_folders[i])
tridesclous 2019-12-17T14:42:21.486614:   File
"/usr/local/lib/python3.6/dist-packages/spikesorters/tridesclous/tridesclous.py",
line 171, in _run
tridesclous 2019-12-17T14:42:21.486618:     peeler.run(duration=None,
progressbar=False)
tridesclous 2019-12-17T14:42:21.486624:   File
"/usr/local/lib/python3.6/dist-packages/tridesclous/peeler.py", line 152,
in run_offline_all_segment
tridesclous 2019-12-17T14:42:21.486631:
self.run_offline_loop_one_segment(seg_num=seg_num, **kargs)
tridesclous 2019-12-17T14:42:21.486639:   File
"/usr/local/lib/python3.6/dist-packages/tridesclous/peeler.py", line 125,
in run_offline_loop_one_segment
tridesclous 2019-12-17T14:42:21.486643:     sig_index, preprocessed_chunk,
total_spike, spikes = self.peeler_engine.process_one_chunk(pos, sigs_chunk)
tridesclous 2019-12-17T14:42:21.486649:   File
"/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_base.py",
line 271, in process_one_chunk
tridesclous 2019-12-17T14:42:21.486658:     spike =
self.classify_and_align_next_spike(peak_ind, peak_chan)
tridesclous 2019-12-17T14:42:21.486663:   File
"/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_base.py",
line 402, in classify_and_align_next_spike
tridesclous 2019-12-17T14:42:21.486668:     cluster_idx, shift =
self.get_best_template(left_ind, peak_chan)
tridesclous 2019-12-17T14:42:21.486673:   File
"/usr/local/lib/python3.6/dist-packages/tridesclous/peeler_engine_geometry.py",
line 353, in get_best_template
tridesclous 2019-12-17T14:42:21.486678:     if s[cluster_idx] >
self.max_float32:
tridesclous 2019-12-17T14:42:21.486706: IndexError: index 9 is out of
bounds for axis 0 with size 7
```

**Comment by samuelgarcia** [comment]
Hi Jeremy,
I fix the bug but at the wrong place.
Thank you for report.
I will try another release very very soon.

**Comment by magland** [comment]
Thanks! Just let me know when it is ready.
J
